
export const examples = [
  {
    id: "ex-b1",
    topicId: "basics",
    title: "Коэффициенты полного уравнения",
    equationLatex: "x^2 - 5x + 6 = 0",
    method: "Определение коэффициентов",
    steps: [
      { text: "Стандартный вид: ax² + bx + c = 0." },
      { latex: "a = 1, \\quad b = -5, \\quad c = 6", text: "" },
      { text: "Уравнение полное — можно применять дискриминант или теорему Виета." },
    ],
    answerLatex: "a=1,\\; b=-5,\\; c=6",
  },
  {
    id: "ex1",
    topicId: "incomplete",
    title: "Неполное уравнение через разложение",
    equationLatex: "x^2 - 5x = 0",
    method: "Разложение на множители",
    steps: [
      { text: "Вынесем x за скобки:" },
      { latex: "x(x - 5) = 0", text: "" },
      { text: "Произведение равно нулю, когда хотя бы один множитель равен нулю:" },
      { latex: "x = 0 \\quad \\text{или} \\quad x - 5 = 0", text: "" },
      { latex: "x_1 = 0, \\quad x_2 = 5", text: "Ответ:" },
    ],
    answerLatex: "x_1 = 0, \\; x_2 = 5",
  },
  {
    id: "ex7",
    topicId: "incomplete",
    title: "Неполное: ax² + c = 0",
    equationLatex: "2x^2 - 18 = 0",
    method: "Изолирование x²",
    steps: [
      { latex: "2x^2 = 18", text: "" },
      { latex: "x^2 = 9", text: "" },
      { latex: "x_1 = 3, \\quad x_2 = -3", text: "Ответ:" },
    ],
    answerLatex: "x_1 = 3, \\; x_2 = -3",
  },
  {
    id: "ex-inc3",
    topicId: "incomplete",
    title: "Неполное: ax² = 0",
    equationLatex: "5x^2 = 0",
    method: "Изолирование",
    steps: [
      { latex: "x^2 = 0", text: "" },
      { latex: "x = 0", text: "Ответ:" },
    ],
    answerLatex: "x = 0",
  },
  {
    id: "ex2",
    topicId: "discriminant",
    title: "Два корня через дискриминант",
    equationLatex: "x^2 - 5x + 6 = 0",
    method: "Дискриминант и формула корней",
    steps: [
      { text: "a = 1, b = -5, c = 6" },
      { latex: "D = (-5)^2 - 4 \\cdot 1 \\cdot 6 = 25 - 24 = 1", text: "" },
      { text: "D > 0 — два корня." },
      { latex: "x_{1,2} = \\frac{5 \\pm \\sqrt{1}}{2} = \\frac{5 \\pm 1}{2}", text: "" },
      { latex: "x_1 = 3, \\quad x_2 = 2", text: "Ответ:" },
    ],
    answerLatex: "x_1 = 3, \\; x_2 = 2",
  },
  {
    id: "ex3",
    topicId: "discriminant",
    title: "Один корень (D = 0)",
    equationLatex: "x^2 - 6x + 9 = 0",
    method: "Дискриминант",
    steps: [
      { text: "a = 1, b = -6, c = 9" },
      { latex: "D = (-6)^2 - 4 \\cdot 1 \\cdot 9 = 36 - 36 = 0", text: "" },
      { text: "D = 0 — один корень." },
      { latex: "x = \\frac{6}{2} = 3", text: "" },
    ],
    answerLatex: "x = 3",
  },
  {
    id: "ex4",
    topicId: "discriminant",
    title: "Нет действительных корней",
    equationLatex: "x^2 + 2x + 5 = 0",
    method: "Дискриминант",
    steps: [
      { text: "a = 1, b = 2, c = 5" },
      { latex: "D = 2^2 - 4 \\cdot 1 \\cdot 5 = 4 - 20 = -16", text: "" },
      { text: "D < 0 — действительных корней нет." },
    ],
    answerLatex: "\\text{действительных корней нет}",
  },
  {
    id: "ex8",
    topicId: "discriminant",
    title: "Дробные корни",
    equationLatex: "2x^2 - 3x - 2 = 0",
    method: "Формула корней",
    steps: [
      { latex: "D = (-3)^2 - 4 \\cdot 2 \\cdot (-2) = 9 + 16 = 25", text: "" },
      { latex: "x_{1,2} = \\frac{3 \\pm 5}{4}", text: "" },
      { latex: "x_1 = 2, \\quad x_2 = -\\frac{1}{2}", text: "Ответ:" },
    ],
    answerLatex: "x_1 = 2, \\; x_2 = -\\frac{1}{2}",
  },
  {
    id: "ex5",
    topicId: "vieta",
    title: "Теорема Виета",
    equationLatex: "x^2 - 7x + 12 = 0",
    method: "Теорема Виета",
    steps: [
      { text: "Ищем два числа, сумма которых 7, а произведение 12:" },
      { latex: "x_1 + x_2 = 7, \\quad x_1 \\cdot x_2 = 12", text: "" },
      { text: "Подходят числа 3 и 4." },
      { latex: "x_1 = 3, \\quad x_2 = 4", text: "Ответ:" },
    ],
    answerLatex: "x_1 = 3, \\; x_2 = 4",
  },
  {
    id: "ex-v2",
    topicId: "vieta",
    title: "Отрицательные корни",
    equationLatex: "x^2 + 5x + 6 = 0",
    method: "Теорема Виета",
    steps: [
      { text: "Сумма корней −5, произведение 6." },
      { latex: "x_1 = -2, \\quad x_2 = -3", text: "Ответ:" },
    ],
    answerLatex: "x_1 = -2, \\; x_2 = -3",
  },
  {
    id: "ex6",
    topicId: "reduction",
    title: "Приведение к стандартному виду",
    equationLatex: "2x^2 = 8x - 6",
    method: "Приведение и дискриминант",
    steps: [
      { text: "Перенесём все слагаемые влево:" },
      { latex: "2x^2 - 8x + 6 = 0", text: "" },
      { text: "Разделим на 2:" },
      { latex: "x^2 - 4x + 3 = 0", text: "" },
      { latex: "D = 16 - 12 = 4", text: "" },
      { latex: "x_{1,2} = \\frac{4 \\pm 2}{2} = 2 \\pm 1", text: "" },
      { latex: "x_1 = 3, \\quad x_2 = 1", text: "Ответ:" },
    ],
    answerLatex: "x_1 = 3, \\; x_2 = 1",
  },
  {
    id: "ex-r2",
    topicId: "reduction",
    title: "Перенос с обеих сторон",
    equationLatex: "x^2 = 5x - 4",
    method: "Приведение",
    steps: [
      { latex: "x^2 - 5x + 4 = 0", text: "Перенос:" },
      { text: "Далее — теорема Виета или дискриминант." },
      { latex: "x_1 = 1, \\quad x_2 = 4", text: "Ответ:" },
    ],
    answerLatex: "x_1 = 1, \\; x_2 = 4",
  },
  {
    id: "ex-d1",
    topicId: "derivatives",
    title: "Производная многочлена",
    equationLatex: "f(x)=3x^2-5x+1",
    method: "Правило степени",
    steps: [
      { text: "Производная от 3x² равна 6x." },
      { text: "Производная от −5x равна −5." },
      { text: "Производная константы 1 равна 0." },
      { latex: "f'(x)=6x-5", text: "Ответ:" },
    ],
    answerLatex: "f'(x)=6x-5",
  },
  {
    id: "ex-d2",
    topicId: "derivatives",
    title: "Угловой коэффициент касательной",
    equationLatex: "f(x)=x^2, \\quad x_0=3",
    method: "Значение производной в точке",
    steps: [
      { latex: "f'(x)=2x", text: "Сначала найдём производную:" },
      { latex: "f'(3)=2\\cdot 3=6", text: "Подставим x₀ = 3:" },
    ],
    answerLatex: "k=6",
  },
  {
    id: "ex-i1",
    topicId: "integrals",
    title: "Неопределённый интеграл",
    equationLatex: "\\int (4x^3-2x)\\,dx",
    method: "Формула степени",
    steps: [
      { latex: "\\int 4x^3\\,dx=x^4", text: "Увеличиваем степень на 1 и делим на новую степень." },
      { latex: "\\int (-2x)\\,dx=-x^2", text: "" },
      { latex: "\\int (4x^3-2x)\\,dx=x^4-x^2+C", text: "Ответ:" },
    ],
    answerLatex: "x^4-x^2+C",
  },
  {
    id: "ex-i2",
    topicId: "integrals",
    title: "Проверка через производную",
    equationLatex: "F(x)=x^3+2x+C",
    method: "Обратная проверка",
    steps: [
      { latex: "F'(x)=3x^2+2", text: "Берём производную первообразной." },
      { text: "Если получили исходную функцию, интеграл найден верно." },
    ],
    answerLatex: "\\int (3x^2+2)\\,dx=x^3+2x+C",
  },
  {
    id: "ex-l1",
    topicId: "limits",
    title: "Предел через подстановку",
    equationLatex: "\\lim_{x\\to 3}(2x+1)",
    method: "Непрерывность",
    steps: [
      { text: "Линейная функция непрерывна, значит можно подставить x = 3." },
      { latex: "2\\cdot 3+1=7", text: "Ответ:" },
    ],
    answerLatex: "7",
  },
  {
    id: "ex-l2",
    topicId: "limits",
    title: "Сокращение неопределённости",
    equationLatex: "\\lim_{x\\to 2}\\frac{x^2-4}{x-2}",
    method: "Разложение на множители",
    steps: [
      { latex: "x^2-4=(x-2)(x+2)", text: "Разложим числитель:" },
      { latex: "\\frac{(x-2)(x+2)}{x-2}=x+2", text: "Сократим общий множитель при x ≠ 2." },
      { latex: "\\lim_{x\\to 2}(x+2)=4", text: "Ответ:" },
    ],
    answerLatex: "4",
  },
];

export function getExamplesByTopic(topicId) {
  return examples.filter((e) => e.topicId === topicId);
}
