
export const problems = [
  // basics
  {
    id: "b1",
    topicId: "basics",
    difficulty: "easy",
    equationLatex: "x^2 - 5x + 6 = 0",
    a: 1,
    b: -5,
    c: 6,
    answer: { type: "two", x1: 2, x2: 3 },
    method: "vieta",
  },
  {
    id: "b2",
    topicId: "basics",
    difficulty: "easy",
    equationLatex: "x^2 + x - 12 = 0",
    a: 1,
    b: 1,
    c: -12,
    answer: { type: "two", x1: -4, x2: 3 },
    method: "discriminant",
  },
  {
    id: "b3",
    topicId: "basics",
    difficulty: "medium",
    equationLatex: "x^2 - 4x + 4 = 0",
    a: 1,
    b: -4,
    c: 4,
    answer: { type: "one", x1: 2, x2: 2 },
    method: "discriminant",
  },
  // incomplete
  {
    id: "e1",
    topicId: "incomplete",
    difficulty: "easy",
    equationLatex: "x^2 - 4x = 0",
    a: 1,
    b: -4,
    c: 0,
    answer: { type: "two", x1: 0, x2: 4 },
    method: "factoring",
  },
  {
    id: "e2",
    topicId: "incomplete",
    difficulty: "easy",
    equationLatex: "x^2 - 9 = 0",
    a: 1,
    b: 0,
    c: -9,
    answer: { type: "two", x1: -3, x2: 3 },
    method: "incomplete",
  },
  {
    id: "e3",
    topicId: "incomplete",
    difficulty: "easy",
    equationLatex: "x^2 + 3x = 0",
    a: 1,
    b: 3,
    c: 0,
    answer: { type: "two", x1: -3, x2: 0 },
    method: "factoring",
  },
  {
    id: "e6",
    topicId: "incomplete",
    difficulty: "easy",
    equationLatex: "3x^2 = 0",
    a: 3,
    b: 0,
    c: 0,
    answer: { type: "one", x1: 0, x2: 0 },
    method: "incomplete",
  },
  {
    id: "m6",
    topicId: "incomplete",
    difficulty: "medium",
    equationLatex: "4x^2 - 12x = 0",
    a: 4,
    b: -12,
    c: 0,
    answer: { type: "two", x1: 0, x2: 3 },
    method: "factoring",
  },
  {
    id: "inc6",
    topicId: "incomplete",
    difficulty: "medium",
    equationLatex: "3x^2 - 27 = 0",
    a: 3,
    b: 0,
    c: -27,
    answer: { type: "two", x1: -3, x2: 3 },
    method: "incomplete",
  },
  // discriminant
  {
    id: "e4",
    topicId: "discriminant",
    difficulty: "easy",
    equationLatex: "x^2 - 2x - 8 = 0",
    a: 1,
    b: -2,
    c: -8,
    answer: { type: "two", x1: -2, x2: 4 },
    method: "discriminant",
  },
  {
    id: "m2",
    topicId: "discriminant",
    difficulty: "medium",
    equationLatex: "x^2 + 2x - 15 = 0",
    a: 1,
    b: 2,
    c: -15,
    answer: { type: "two", x1: -5, x2: 3 },
    method: "discriminant",
  },
  {
    id: "m3",
    topicId: "discriminant",
    difficulty: "medium",
    equationLatex: "x^2 - 10x + 25 = 0",
    a: 1,
    b: -10,
    c: 25,
    answer: { type: "one", x1: 5, x2: 5 },
    method: "discriminant",
  },
  {
    id: "m4",
    topicId: "discriminant",
    difficulty: "medium",
    equationLatex: "2x^2 - 5x + 2 = 0",
    a: 2,
    b: -5,
    c: 2,
    answer: { type: "two", x1: 0.5, x2: 2 },
    method: "discriminant",
  },
  {
    id: "h1",
    topicId: "discriminant",
    difficulty: "hard",
    equationLatex: "x^2 + 4x + 7 = 0",
    a: 1,
    b: 4,
    c: 7,
    answer: { type: "none" },
    method: "discriminant",
  },
  {
    id: "h2",
    topicId: "discriminant",
    difficulty: "hard",
    equationLatex: "3x^2 - 2x - 1 = 0",
    a: 3,
    b: -2,
    c: -1,
    answer: { type: "two", x1: -1 / 3, x2: 1 },
    method: "discriminant",
  },
  {
    id: "h4",
    topicId: "discriminant",
    difficulty: "hard",
    equationLatex: "2x^2 + 3x - 5 = 0",
    a: 2,
    b: 3,
    c: -5,
    answer: { type: "two", x1: -2.5, x2: 1 },
    method: "discriminant",
  },
  {
    id: "h5",
    topicId: "discriminant",
    difficulty: "hard",
    equationLatex: "x^2 - 3x + 5 = 0",
    a: 1,
    b: -3,
    c: 5,
    answer: { type: "none" },
    method: "discriminant",
  },
  // vieta
  {
    id: "e5",
    topicId: "vieta",
    difficulty: "easy",
    equationLatex: "x^2 + 5x + 6 = 0",
    a: 1,
    b: 5,
    c: 6,
    answer: { type: "two", x1: -3, x2: -2 },
    method: "vieta",
  },
  {
    id: "m1",
    topicId: "vieta",
    difficulty: "medium",
    equationLatex: "x^2 - 7x + 12 = 0",
    a: 1,
    b: -7,
    c: 12,
    answer: { type: "two", x1: 3, x2: 4 },
    method: "vieta",
  },
  {
    id: "m5",
    topicId: "vieta",
    difficulty: "medium",
    equationLatex: "x^2 + x - 20 = 0",
    a: 1,
    b: 1,
    c: -20,
    answer: { type: "two", x1: -5, x2: 4 },
    method: "vieta",
  },
  {
    id: "v4",
    topicId: "vieta",
    difficulty: "easy",
    equationLatex: "x^2 - 8x + 15 = 0",
    a: 1,
    b: -8,
    c: 15,
    answer: { type: "two", x1: 3, x2: 5 },
    method: "vieta",
  },
  {
    id: "v5",
    topicId: "vieta",
    difficulty: "medium",
    equationLatex: "x^2 + 9x + 20 = 0",
    a: 1,
    b: 9,
    c: 20,
    answer: { type: "two", x1: -4, x2: -5 },
    method: "vieta",
  },
  {
    id: "v6",
    topicId: "vieta",
    difficulty: "hard",
    equationLatex: "x^2 - 2x - 24 = 0",
    a: 1,
    b: -2,
    c: -24,
    answer: { type: "two", x1: -4, x2: 6 },
    method: "vieta",
  },
  // reduction
  {
    id: "h3",
    topicId: "reduction",
    difficulty: "hard",
    equationLatex: "x^2 = 5x - 4",
    a: 1,
    b: -5,
    c: 4,
    answer: { type: "two", x1: 1, x2: 4 },
    method: "discriminant",
  },
  {
    id: "h6",
    topicId: "reduction",
    difficulty: "hard",
    equationLatex: "6x^2 = 24x - 18",
    a: 6,
    b: -24,
    c: 18,
    answer: { type: "two", x1: 1, x2: 3 },
    method: "discriminant",
  },
  {
    id: "r3",
    topicId: "reduction",
    difficulty: "medium",
    equationLatex: "3x^2 = 12x - 9",
    a: 3,
    b: -12,
    c: 9,
    answer: { type: "two", x1: 1, x2: 3 },
    method: "discriminant",
  },
  {
    id: "r4",
    topicId: "reduction",
    difficulty: "easy",
    equationLatex: "x^2 + 3x = 10",
    a: 1,
    b: 3,
    c: -10,
    answer: { type: "two", x1: -5, x2: 2 },
    method: "discriminant",
  },
  {
    id: "r5",
    topicId: "reduction",
    difficulty: "medium",
    equationLatex: "2x^2 = 10x - 8",
    a: 2,
    b: -10,
    c: 8,
    answer: { type: "two", x1: 1, x2: 4 },
    method: "discriminant",
  },
];

export const difficultyLabels = {
  all: "Все",
  easy: "Лёгкий",
  medium: "Средний",
  hard: "Сложный",
};

export function getProblemsByTopic(topicId) {
  return problems.filter((p) => p.topicId === topicId);
}
